env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent: ['error', 4]
  semi: ['error', 'always']
  object-curly-spacing: ['error', 'always']
  array-bracket-spacing: ['error', 'always']
  computed-property-spacing: ['error', 'always']
  space-before-blocks: ['error', 'always']
  space-before-function-paren: ['error', 'always']
  space-in-parens: ['error', 'never']
  comma-spacing: ['error']
  quote-props: ['error', 'as-needed']
  quotes: ['error', single, { "allowTemplateLiterals": true }]
  key-spacing: ['error', { "beforeColon": false, "afterColon":true }]
  keyword-spacing: ['error']
  space-infix-ops: ['error', { "int32Hint": false }]
  semi-spacing: ['error', {"before": false, "after": true}]
  react/prop-types: ['off']
  react/display-name: ['off']
  react-hooks/exhaustive-deps: ['error']

